'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Header, Footer } from '../components/site';
import { supabase } from '../../lib/supabase';

export default function DemoPage(){
 const [form,setForm]=useState({name:'',phone:'',email:'',whatsapp:'',date:'',time:'',notes:''});
 const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
 function set(k:keyof typeof form,v:string){setForm(f=>({...f,[k]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.from('demo_requests').insert({name:form.name.trim(),phone:form.phone.trim(),email:form.email.trim()||null,whatsapp:form.whatsapp.trim()||null,preferred_date:form.date||null,preferred_time:form.time||null,notes:form.notes.trim()||null});if(error)throw error;setDone(true)}catch(err){setError(err instanceof Error?err.message:'Unable to send your request. Please try again.')}finally{setBusy(false)}}
 return <><Header/><main className="form-page"><div className="form-intro"><div className="eyebrow">Start with a free demo</div><h1>Schedule a Free Demo Class.</h1><p>Give us a few details and a convenient time. The Saral Vigyan team will contact you and confirm the class.</p></div>{done?<div className="form-card success-card"><div className="success">✓</div><h2>Request received.</h2><p>Your demo request has been sent to the TutorVerse system for Saral Vigyan follow-up.</p><Link href="/" className="btn primary">Back to TutorVerse →</Link></div>:<form className="form-card" onSubmit={submit}><div className="two"><label>Student / Parent name<input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your name"/></label><label>Phone<input required value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="Mobile number"/></label></div><div className="two"><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com"/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>set('whatsapp',e.target.value)} placeholder="WhatsApp number (optional)"/></label></div><div className="two"><label>Preferred date<input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label><label>Preferred time<input type="time" value={form.time} onChange={e=>set('time',e.target.value)}/></label></div><label>What do you need?<textarea rows={4} value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Class, subject, grade, board or exam (optional)"/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?'Sending…':'Schedule Free Demo →'}</button><p className="switch">Prefer an account? <Link href="/signup">Create a student account</Link></p></form>}</main><Footer/></>
}
