'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Header, Footer } from '../components/site'
import { supabase } from '../../lib/supabase'

export default function UpdatePasswordPage() {
  const [password,setPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState(''); const [ready,setReady]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  useEffect(()=>{let active=true;const checkSession=async()=>{const {data}=await supabase.auth.getSession();if(active&&data.session)setReady(true)};checkSession();const {data:listener}=supabase.auth.onAuthStateChange((event,session)=>{if(!active)return;if(event==='PASSWORD_RECOVERY'&&session)setReady(true)});return()=>{active=false;listener.subscription.unsubscribe()}},[])
  async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');if(password.length<8){setError('Please use a password of at least 8 characters.');return}if(password!==confirmPassword){setError('The two passwords do not match.');return}setBusy(true);try{const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;setMessage('Your password has been changed. You can now log in with the new password.');await supabase.auth.signOut()}catch(err){setError(err instanceof Error?err.message:'Unable to change your password. Please request a new reset email.')}finally{setBusy(false)}}
  return <><Header/><style>{`header a > span:first-child{background:#fff!important;color:#6257e8!important}`}</style><main className="auth"><div className="auth-card"><div className="eyebrow">TutorVerse account recovery</div><h1>Choose a new password.</h1>{message?<><p className="rounded-xl bg-green-50 p-3 text-sm font-semibold text-green-700">{message}</p><Link href="/login" className="btn primary full">Go to login →</Link></>:!ready?<><p>Open the password-reset link from your email on this device. If you already opened it, wait a moment and refresh this page.</p>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<Link href="/forgot-password" className="btn primary full">Request a new reset email →</Link></>:<form onSubmit={submit}><p>Set a new password for your TutorVerse account.</p><label>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label><label>Confirm new password<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={8} required/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?'Saving…':'Set new password →'}</button></form>}</div></main><Footer/></>
}
