'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Header, Footer } from '../components/site';

const cards=[['Leads','18','New enquiries'],['Students','42','Active'],['Tutor applications','7','Awaiting review'],['Classrooms','16','Running'],['Today’s classes','9','2 currently live'],['Pending notifications','4','Need attention']];

export default function AdminDashboard(){
 const [section,setSection]=useState('Overview'); const [saved,setSaved]=useState(false);
 const nav=['Overview','Students','Parents','Tutors','Classrooms','Calendar','Class reports','Content','Assessments','Payments','Tutor search','Feedback','Notifications'];
 return <><Header/><main className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-col gap-5 lg:flex-row"><aside className="w-full shrink-0 lg:w-60"><div className="rounded-3xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Saral Vigyan</p><h1 className="mt-2 text-2xl font-black">Admin control</h1><p className="mt-1 text-xs text-slate-400">TutorVerse operations</p><div className="mt-5 grid gap-1">{nav.map(n=><button key={n} onClick={()=>setSection(n)} className={`rounded-xl px-3 py-2 text-left text-sm font-semibold ${section===n?'bg-white text-slate-950':'text-slate-300 hover:bg-white/10'}`}>{n}</button>)}</div></div></aside><section className="min-w-0 flex-1"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-slate-400">Admin dashboard</p><h2 className="mt-2 text-4xl font-black tracking-tight">{section}</h2><p className="mt-2 text-slate-500">The Saral Vigyan team controls what is created, published, assigned and communicated.</p></div><Link href="/" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">View public site →</Link></div>
 {section==='Overview'?<><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(c=><div key={c[0]} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{c[0]}</p><p className="mt-2 text-3xl font-black">{c[1]}</p><p className="mt-1 text-xs text-slate-400">{c[2]}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6"><h3 className="text-xl font-black">Today’s operations</h3><div className="mt-4 grid gap-3 text-sm"><div className="rounded-2xl bg-slate-50 p-4"><b>5:30 PM · Physics · Home tuition</b><p className="mt-1 text-slate-500">Tutor: Aarav · Student: Aarav Sharma · Parent reminder queued for 5:00 PM</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>6:00 PM · Chemistry · Online</b><p className="mt-1 text-slate-500">Google Meet link ready · parent notification queued</p></div></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><h3 className="text-xl font-black">Quick create</h3><p className="mt-1 text-sm text-slate-500">The production admin can create these directly in the database-backed version.</p><div className="mt-4 grid grid-cols-2 gap-2">{['Student','Parent','Tutor','Classroom','Class','Assessment','Material','Payment'].map(x=><button key={x} onClick={()=>setSaved(true)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm font-bold hover:bg-slate-50">+ {x}</button>)}</div>{saved&&<p className="mt-4 text-sm font-semibold text-slate-600">✓ Creation workflow selected. Production version will open the relevant form and save to Supabase.</p>}</div></div></>:<div className="mt-7 rounded-3xl border border-slate-200 bg-white p-7"><h3 className="text-xl font-black">{section} workspace</h3><p className="mt-2 max-w-2xl text-slate-500">This module is now reserved in the admin architecture. The next database-backed iteration will give the Saral Vigyan team create, edit, assign, publish and audit controls here.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{['Create','Edit','View history'].map(a=><button key={a} onClick={()=>setSaved(true)} className="rounded-2xl bg-slate-50 p-5 text-left font-black">{a}<p className="mt-1 text-xs font-normal text-slate-500">Ready for Supabase-backed workflow</p></button>)}</div>{saved&&<p className="mt-5 text-sm font-semibold text-slate-600">✓ Workflow action selected.</p>}</div>}</section></div></main><Footer/></>;
}
