'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import MaterialsPanel from './materials-panel';
import PeoplePanel from './people-panel';
import TutorsPanel from './tutors-panel';
import { Header, Footer } from '../components/site';
import Link from 'next/link';

const nav=['Overview','Users & Managers','Students','Parents','Tutors','Classrooms','Calendar','Class reports','Content','Assessments','Payments','Tutor search','Feedback','Notifications'];

export default function AdminDashboard(){
 const [authorized,setAuthorized]=useState(false);const [checking,setChecking]=useState(true);const [section,setSection]=useState('Overview');
 const [stats,setStats]=useState({students:0,classrooms:0,classes:0,tutors:0,assessments:0,payments:0});
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return;}const {data:profile,error}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(!active)return;if(error||!profile||!['admin','staff'].includes(profile.role)){await supabase.auth.signOut();window.location.href='/login';return;}setAuthorized(true);setChecking(false);const tables=['students','classrooms','classes','tutors','assessments','payments'] as const;const counts=await Promise.all(tables.map(t=>supabase.from(t).select('id',{count:'exact',head:true})));if(active)setStats({students:counts[0].count||0,classrooms:counts[1].count||0,tutors:counts[3].count||0,classes:counts[2].count||0,assessments:counts[4].count||0,payments:counts[5].count||0});})();return()=>{active=false}},[]);
 async function logout(){await supabase.auth.signOut();window.location.href='/login'}
 if(checking)return <><Header/><main className="mx-auto max-w-3xl px-5 py-20"><div className="rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><p className="text-sm font-bold uppercase tracking-[.2em] text-slate-400">TutorVerse secure access</p><h1 className="mt-3 text-2xl font-black">Checking administrator access…</h1></div></main><Footer/></>;
 if(!authorized)return null;
 const cards=[['Students',stats.students],['Tutors',stats.tutors],['Classrooms',stats.classrooms],['Classes',stats.classes],['Assessments',stats.assessments],['Payments',stats.payments]];
 return <><Header/><main className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-col gap-5 lg:flex-row"><aside className="w-full shrink-0 lg:w-60"><div className="rounded-3xl bg-slate-950 p-4 text-white"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Saral Vigyan</p><h1 className="mt-2 text-2xl font-black">Admin control</h1><p className="mt-1 text-xs text-slate-400">TutorVerse operations</p></div><button onClick={logout} className="rounded-lg border border-white/20 px-2 py-1 text-xs font-bold text-white hover:bg-white/10">Logout</button></div><div className="mt-5 grid gap-1">{nav.map(n=><button key={n} onClick={()=>setSection(n)} className={`rounded-xl px-3 py-2 text-left text-sm font-semibold ${section===n?'bg-white text-slate-950':'text-slate-300 hover:bg-white/10'}`}>{n}</button>)}</div></div></aside><section className="min-w-0 flex-1"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-slate-400">Admin dashboard</p><h2 className="mt-2 text-4xl font-black tracking-tight">{section}</h2><p className="mt-2 text-slate-500">Saral Vigyan controls the managed TutorVerse learning journey.</p></div><div className="flex gap-2"><button onClick={logout} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">Logout</button><Link href="/" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">View public site →</Link></div></div>
 {section==='Overview'?<><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(c=><div key={c[0]} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{c[0]}</p><p className="mt-2 text-3xl font-black">{c[1]}</p><p className="mt-1 text-xs text-slate-400">Live database count</p></div>)}</div><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-7"><h3 className="text-xl font-black">Control centre</h3><p className="mt-2 max-w-3xl text-slate-500">The main Admin can manage TutorVerse records. Managers are created with module-by-module permissions; Managers can view/create/edit/archive only and never receive permanent Delete rights.</p></div></>:section==='Content'?<MaterialsPanel/>:section==='Users & Managers'?<PeoplePanel/>:section==='Tutors'?<TutorsPanel/>:<div className="mt-7 rounded-3xl border border-slate-200 bg-white p-7"><h3 className="text-xl font-black">{section} workspace</h3><p className="mt-2 max-w-2xl text-slate-500">This module will use the same real Supabase records, archive controls and role permissions as the rest of the Admin control centre. No browser-only operational data is intended.</p></div>}
 </section></div></main><Footer/></>;
}
