'use client';
import { useEffect,useState } from 'react';
import MaterialsPanel from './materials-panel'; import PeoplePanel from './people-panel'; import TutorsPanel from './tutors-panel';
import { Header,Footer } from '../components/site'; import Link from 'next/link'; import { supabase } from '../../lib/supabase';
const nav=['Overview','Demo leads','Users & Managers','Students','Parents','Tutors','Classrooms','Calendar','Class reports','Content','Assessments','Payments','Tutor search','Feedback','Notifications'];
const cols=(heads:string[],rows:any[],render:(r:any)=>any[])=> <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{heads.map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} className="border-t border-slate-100">{render(r).map((v,j)=><td key={j} className="px-5 py-3 text-slate-600">{v??'—'}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={heads.length} className="px-5 py-12 text-center text-slate-500">No records found.</td></tr>}</tbody></table></div>;
export default function AdminDashboard(){
 const [authorized,setAuthorized]=useState(false),[checking,setChecking]=useState(true),[section,setSection]=useState('Overview'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [stats,setStats]=useState({students:0,classrooms:0,classes:0,tutors:0,assessments:0,payments:0,demos:0}); const [demos,setDemos]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[parents,setParents]=useState<any[]>([]),[classrooms,setClassrooms]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]);
 async function loadSection(s:string){setLoading(true);setError('');try{
  if(s==='Demo leads'){const {data,error}=await supabase.from('demo_requests').select('*').order('created_at',{ascending:false});if(error)throw error;setDemos(data||[])}
  if(s==='Students'){const {data,error}=await supabase.from('students').select('*,profile:profiles(full_name,phone)').order('created_at',{ascending:false});if(error)throw error;setStudents(data||[])}
  if(s==='Parents'){const {data,error}=await supabase.from('parents').select('*,profile:profiles(full_name,phone)').order('created_at',{ascending:false});if(error)throw error;setParents(data||[])}
  if(s==='Classrooms'){const {data,error}=await supabase.from('classrooms').select('*,subject:subjects(name),tutor:tutors(profile:profiles(full_name))').order('created_at',{ascending:false});if(error)throw error;setClassrooms(data||[])}
  if(s==='Class reports'){const {data,error}=await supabase.from('class_reports').select('*,class:classes(starts_at,status,classroom:classrooms(name),created_by_profile:profiles(full_name))').order('created_at',{ascending:false});if(error)throw error;setReports(data||[])}
 }catch(e){setError(e instanceof Error?e.message:'Unable to load live database records.')}finally{setLoading(false)}}
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return}const {data:profile,error}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(!active)return;if(error||!profile||!['admin','staff'].includes(profile.role)){await supabase.auth.signOut();window.location.href='/login';return}setAuthorized(true);setChecking(false);const tables=['students','classrooms','classes','tutors','assessments','payments','demo_requests'] as const;const counts=await Promise.all(tables.map(t=>supabase.from(t).select('id',{count:'exact',head:true})));if(active)setStats({students:counts[0].count||0,classrooms:counts[1].count||0,classes:counts[2].count||0,tutors:counts[3].count||0,assessments:counts[4].count||0,payments:counts[5].count||0,demos:counts[6].count||0})})();return()=>{active=false}},[]);
 useEffect(()=>{if(authorized&&section!=='Overview'&&section!=='Users & Managers'&&section!=='Tutors'&&section!=='Content')loadSection(section)},[authorized,section]);
 async function logout(){await supabase.auth.signOut();window.location.href='/login'}
 if(checking)return <><Header/><main className="mx-auto max-w-3xl px-5 py-20"><div className="rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><p className="text-sm font-bold uppercase tracking-[.2em] text-slate-400">TutorVerse secure access</p><h1 className="mt-3 text-2xl font-black">Checking administrator access…</h1></div></main><Footer/></>;
 if(!authorized)return null; const cards=[['Students',stats.students],['Tutors',stats.tutors],['Classrooms',stats.classrooms],['Classes',stats.classes],['Demo leads',stats.demos],['Assessments',stats.assessments],['Payments',stats.payments]];
 const panel=section==='Overview'?<><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><div key={c[0]} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{c[0]}</p><p className="mt-2 text-3xl font-black">{c[1]}</p><p className="mt-1 text-xs text-slate-400">Live database count</p></div>)}</div><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-7"><h3 className="text-xl font-black">Control centre</h3><p className="mt-2 max-w-3xl text-slate-500">Every operational module is connected to the live Supabase database.</p></div></>:
 section==='Demo leads'?<div className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h3 className="text-xl font-black">All demo leads</h3><p className="mt-1 text-sm text-slate-500">Live records from Schedule a Free Demo Class.</p></div>{loading?<div className="p-8 text-center">Loading live leads…</div>:cols(['Name','Phone','Email','WhatsApp','Class / Grade','Board','Subject','Competition','Preferred date','Preferred time','Additional requirements','Status','Created'],demos,d=>[d.name,d.phone,d.email,d.whatsapp,d.grade,d.board,d.subject,d.competition,d.preferred_date,d.preferred_time?String(d.preferred_time).slice(0,5):null,d.notes,d.status,d.created_at?new Date(d.created_at).toLocaleString():null])}</div>:
 section==='Students'?<div className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h3 className="text-xl font-black">All students</h3></div>{loading?<div className="p-8 text-center">Loading students…</div>:cols(['Student','Phone','Email / Account','Class / Grade','Board','School','City','Created'],students,s=>[s.profile?.full_name,s.profile?.phone,s.profile?.email,s.grade,s.board,s.school,s.city,s.created_at?new Date(s.created_at).toLocaleDateString():null])}</div>:
 section==='Parents'?<div className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h3 className="text-xl font-black">All parents</h3></div>{loading?<div className="p-8 text-center">Loading parents…</div>:cols(['Parent','Phone','Email / Account','Relationship','Created'],parents,p=>[p.profile?.full_name,p.profile?.phone,p.profile?.email,p.relationship,p.created_at?new Date(p.created_at).toLocaleDateString():null])}</div>:
 section==='Classrooms'?<div className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h3 className="text-xl font-black">All classrooms</h3></div>{loading?<div className="p-8 text-center">Loading classrooms…</div>:cols(['Classroom','Subject','Tutor','Mode','Location','Active','Created'],classrooms,c=>[c.name,c.subject?.name,c.tutor?.profile?.full_name,c.mode,c.location,c.active?'Yes':'No',c.created_at?new Date(c.created_at).toLocaleDateString():null])}</div>:
 section==='Class reports'?<div className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h3 className="text-xl font-black">All class reports</h3></div>{loading?<div className="p-8 text-center">Loading class reports…</div>:cols(['Classroom','Class date','Status','Topic','Covered','Homework','Tutor remarks','Created'],reports,r=>[r.class?.classroom?.name,r.class?.starts_at?new Date(r.class.starts_at).toLocaleString():null,r.class?.status,r.topic,r.covered,r.homework,r.tutor_remarks,r.created_at?new Date(r.created_at).toLocaleString():null])}</div>:
 section==='Content'?<MaterialsPanel/>:section==='Users & Managers'?<PeoplePanel/>:section==='Tutors'?<TutorsPanel/>:<div className="mt-7 rounded-3xl border border-slate-200 bg-white p-7"><h3 className="text-xl font-black">{section}</h3><p className="mt-2 max-w-2xl text-slate-500">This module is ready for live database wiring.</p></div>;
 return <><Header/><main className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-col gap-5 lg:flex-row"><aside className="w-full shrink-0 lg:w-60"><div className="rounded-3xl bg-slate-950 p-4 text-white"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Saral Vigyan</p><h1 className="mt-2 text-2xl font-black">Admin control</h1><p className="mt-1 text-xs text-slate-400">TutorVerse operations</p></div><button onClick={logout} className="rounded-lg border border-white/20 px-2 py-1 text-xs font-bold">Logout</button></div><div className="mt-5 grid gap-1">{nav.map(n=><button key={n} onClick={()=>setSection(n)} className={`rounded-xl px-3 py-2 text-left text-sm font-semibold ${section===n?'bg-white text-slate-950':'text-slate-300 hover:bg-white/10'}`}>{n}</button>)}</div></div></aside><section className="min-w-0 flex-1"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-slate-400">Admin dashboard</p><h2 className="mt-2 text-4xl font-black tracking-tight">{section}</h2><p className="mt-2 text-slate-500">Live TutorVerse operational data.</p></div><div className="flex gap-2"><button onClick={()=>section!=='Overview'&&loadSection(section)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">Refresh</button><button onClick={logout} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">Logout</button><Link href="/" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">View public site →</Link></div></div>{error&&<div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{panel}</section></div></main><Footer/></>;
}
