'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import ChangePasswordButton from './change-password-button';

const modules=['Students','Parents','Tutors','Classrooms','Calendar','Class reports','Content','Assessments','Payments','Tutor search','Feedback','Notifications'];
const actions=['view','create','edit','archive','deactivate'] as const;
type Perm={can_view:boolean;can_create:boolean;can_edit:boolean;can_archive:boolean;can_deactivate:boolean};
const blank=():Perm=>({can_view:false,can_create:false,can_edit:false,can_archive:false,can_deactivate:false});

export default function PeoplePanel({isAdmin=true}:{isAdmin?:boolean}){
 const [role,setRole]=useState<'student'|'parent'|'tutor'|'manager'>('manager');
 const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [phone,setPhone]=useState(''); const [password,setPassword]=useState('');
 const [perms,setPerms]=useState<Record<string,Perm>>(()=>Object.fromEntries(modules.map(m=>[m,blank()])));
 const [managers,setManagers]=useState<any[]>([]); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
 async function loadManagers(){const {data}=await supabase.from('profiles').select('id,full_name,phone,role,created_at,is_active,archived_at').eq('role','manager').order('created_at',{ascending:false});setManagers(data||[])}
 useEffect(()=>{loadManagers()},[]);
 function toggle(module:string,action:typeof actions[number]){setPerms(p=>({...p,[module]:{...p[module],[`can_${action}`]:!p[module][`can_${action}` as keyof Perm]}}))}
 function allView(){setPerms(p=>Object.fromEntries(modules.map(m=>[m,{...p[m],can_view:true}]))) }
 async function createAccount(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');const {data,error}=await supabase.functions.invoke('admin-create-account',{body:{full_name:name,email,password,phone,role}});if(error||data?.error){setMessage(error?.message||data?.error||'Could not create account.');setSaving(false);return;}if(role==='manager'){const rows=modules.filter(m=>Object.values(perms[m]).some(Boolean)).map(m=>({manager_id:data.user_id,module:m,can_view:perms[m].can_view,can_create:perms[m].can_create,can_edit:perms[m].can_edit,can_archive:perms[m].can_archive,can_deactivate:perms[m].can_deactivate,can_delete:false}));if(rows.length){const {error:pe}=await supabase.from('manager_permissions').upsert(rows,{onConflict:'manager_id,module'});if(pe){setMessage('Account created, but permissions could not be saved: '+pe.message);setSaving(false);return;}}}setMessage(`✓ ${role[0].toUpperCase()+role.slice(1)} account created. Email is already confirmed; no invitation email is required.`);setName('');setEmail('');setPhone('');setPassword('');setPerms(Object.fromEntries(modules.map(m=>[m,blank()])));await loadManagers();setSaving(false)}
 return <div className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr]">
  {isAdmin?<div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">User administration</p><h3 className="mt-2 text-2xl font-black">Create account</h3><p className="mt-2 text-sm text-slate-500">Main Admin creates accounts directly. Managers can never receive permanent Delete permission.</p>
   <form onSubmit={createAccount} className="mt-6 grid gap-4">
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Full name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label><label className="text-sm font-bold">Role<select value={role} onChange={e=>setRole(e.target.value as any)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"><option value="manager">Manager</option><option value="student">Student</option><option value="parent">Parent</option><option value="tutor">Tutor</option></select></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label><label className="text-sm font-bold">Phone / WhatsApp <span className="font-normal text-slate-400">optional</span><input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label></div>
    <label className="text-sm font-bold">Temporary password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/><span className="mt-1 block text-xs font-normal text-slate-400">At least 8 characters. The user can later use Forgot password.</span></label>
    {role==='manager'&&<div><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-bold">Manager permissions</p><p className="text-xs text-slate-400">Managers can View/Create/Edit/Archive/Deactivate only where granted. Delete is permanently locked.</p></div><button type="button" onClick={allView} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Give View to all</button></div><div className="mt-3 overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-3 text-left">Module</th>{actions.map(a=><th key={a} className="p-3">{a}</th>)}<th className="p-3">Delete</th></tr></thead><tbody className="divide-y divide-slate-100">{modules.map(m=><tr key={m}><td className="p-3 font-semibold">{m}</td>{actions.map(a=><td key={a} className="p-3 text-center"><input aria-label={`${m} ${a}`} type="checkbox" checked={perms[m][`can_${a}` as keyof Perm]} onChange={()=>toggle(m,a)}/></td>)}<td className="p-3 text-center text-slate-300">🔒</td></tr>)}</tbody></table></div></div>}
    <button disabled={saving} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?'Creating…':`Create ${role} account →`}</button>{message&&<p className={`rounded-xl px-4 py-3 text-sm font-semibold ${message.startsWith('✓')?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{message}</p>}
   </form>
  </div>:<div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">Manager access</p><h3 className="mt-2 text-2xl font-black">No account creation</h3><p className="mt-2 text-sm text-slate-500">Managers can operate only within the permissions assigned by the Main Admin. Permanent Delete is never available.</p></div>}
  <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">Managers</p><h3 className="mt-2 text-2xl font-black">Manager accounts</h3>{managers.length===0?<div className="mt-6 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No Managers created yet.</div>:<div className="mt-5 grid gap-3">{managers.map(m=><div key={m.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="font-black">{m.full_name}</p><p className="mt-1 text-sm text-slate-500">Phone: {m.phone||'null'}</p><p className="mt-1 text-sm text-slate-500">Active: {m.is_active===undefined?'null':String(m.is_active)} · Archived: {m.archived_at?new Date(m.archived_at).toLocaleString():'null'}</p><div className="mt-3 flex gap-2"><ChangePasswordButton profileId={m.id} role="manager" name={m.full_name}/></div><p className="mt-2 text-xs text-slate-400">Manager · permissions stored in TutorVerse</p></div>)}</div>}</div>
 </div>
}
