'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import ChangePasswordButton from './change-password-button';
const show=(v:any)=>v===null||v===undefined?'null':Array.isArray(v)?(v.length?v.join(', '):'null'):typeof v==='boolean'?(v?'true':'false'):String(v); const date=(v:any)=>v?new Date(v).toLocaleString():'null';
interface Tutor { id:string; profile_id:string; approved:boolean|null; experience_years:number|null; bio:string|null; city:string|null; modes:string[]|null; created_at:string; address_line:string|null; area:string|null; state:string|null; pincode:string|null; latitude:number|null; longitude:number|null; location_accuracy_m:number|null; profile?:{id:string;full_name:string|null;role:string|null;phone:string|null;whatsapp_opt_in:boolean|null;created_at:string|null;is_active:boolean|null;archived_at:string|null}|null; email:string|null; }
async function manage(action:'delete'|'archive'|'deactivate',profileId:string){const label=action==='delete'?'PERMANENTLY DELETE':action.toUpperCase();if(!window.confirm(`Are you sure you want to ${label} this tutor?${action==='delete'?' This cannot be undone.':''}`))return;const {data,error}=await supabase.functions.invoke('admin-manage-people',{body:{action,role:'tutor',profile_id:profileId}});alert(error?.message||data?.error||data?.message||'Done.');if(!error&&!data?.error)window.dispatchEvent(new Event('tutorverse-refresh-tutors'))}
export default function TutorsPanel({isAdmin=true,userRole='admin',canArchive=false,canDeactivate=false}:{isAdmin?:boolean;userRole?:string;canArchive?:boolean;canDeactivate?:boolean}){
 const [tutors,setTutors]=useState<Tutor[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
 async function loadTutors(){setLoading(true);const {data,error}=await supabase.functions.invoke('admin-manage-people',{body:{action:'list',role:'tutor'}});if(error||data?.error){setMessage(error?.message||data?.error||'Unable to load tutors.');setTutors([])}else{setTutors((data?.records||[]) as Tutor[]);setMessage('')}setLoading(false)}
 useEffect(()=>{loadTutors();const f=()=>loadTutors();window.addEventListener('tutorverse-refresh-tutors',f);return()=>window.removeEventListener('tutorverse-refresh-tutors',f)},[]);
 return <div className="mt-7"><div className="flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:flex-row md:items-center md:justify-between"><div><h3 className="text-xl font-black">Tutor directory</h3><p className="mt-1 text-sm text-slate-500">Every tutor and profile field is shown. Blank database values are displayed as <b>null</b>.</p></div><button onClick={loadTutors} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold hover:bg-slate-50">Refresh</button></div>{message&&<div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{message}</div>}<div className="mt-4 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{loading?<div className="p-8 text-center text-sm text-slate-500">Loading tutors…</div>:tutors.length===0?<div className="p-8 text-center"><p className="font-bold">No tutors found.</p></div>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{['ID','Profile ID','Name','Email','Phone','Role','WhatsApp opt-in','Active','Archived at','Approved','Experience years','Bio','City','Modes','Address','Area','State','PIN','Latitude','Longitude','Location accuracy (m)','Created','Actions'].map(h=><th key={h} className="px-5 py-4 whitespace-nowrap">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{tutors.map(t=>{const p=t.profile;return <tr key={t.id} className="hover:bg-slate-50/70 align-top">{[show(t.id),show(t.profile_id),show(p?.full_name),show(t.email),show(p?.phone),show(p?.role),show(p?.whatsapp_opt_in),show(p?.is_active),date(p?.archived_at),show(t.approved),show(t.experience_years),show(t.bio),show(t.city),show(t.modes),show(t.address_line),show(t.area),show(t.state),show(t.pincode),show(t.latitude),show(t.longitude),show(t.location_accuracy_m),date(t.created_at),<div className="flex gap-2">{canArchive&&<button onClick={()=>manage('archive',t.profile_id)} className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">Archive</button>}{canDeactivate&&<button onClick={()=>manage('deactivate',t.profile_id)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold">Deactivate</button>}{isAdmin&&<><ChangePasswordButton profileId={t.profile_id} role="tutor" name={p?.full_name}/><button onClick={()=>manage('delete',t.profile_id)} className="rounded-lg bg-rose-600 px-3 py-1.5 text-xs font-bold text-white">Delete</button></>}</div>].map((v,j)=><td key={j} className="px-5 py-4 text-slate-600 whitespace-nowrap">{v}</td>)}</tr>})}</tbody></table></div>}</div><p className="mt-3 text-xs text-slate-400">Full address and coordinates are administrative matching information. They should not be shown on the public tutor directory.</p></div>;
}
