'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

export function Header(){
  const [signedIn,setSignedIn]=useState(false);
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active)setSignedIn(!!data.session)});const {data:listener}=supabase.auth.onAuthStateChange((_e,session)=>setSignedIn(!!session));return()=>{active=false;listener.subscription.unsubscribe()}},[]);
  async function logout(){await supabase.auth.signOut();window.location.href='/login'}
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-3"><Link href="/" className="shrink-0"><img src="/tutorverse.svg" alt="TutorVerse.in" className="h-16 w-auto object-contain"/></Link><div className="hidden items-center gap-3 xl:flex"><span className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">Powered by</span><img src="/saralvigyan.svg" alt="Saral Vigyan" className="h-9 w-[205px] object-contain object-left"/></div><nav className="hidden items-center gap-6 text-sm font-semibold text-slate-600 lg:flex"><Link href="/demo" className="text-[#087ee8]">Schedule a Free Demo</Link><Link href="/subjects">Subjects</Link><Link href="/become-a-tutor">Join as a Tutor</Link></nav><div className="flex items-center gap-1">{signedIn?<button onClick={logout} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-700">Log out</button>:<><Link href="/login" className="rounded-xl px-3 py-2 text-sm font-bold text-slate-700">Log in</Link><Link href="/signup" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white shadow-lg">Get started</Link></>}</div></div></header>
}

export function Footer(){return <footer className="mt-20 border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 md:grid-cols-4"><div><img src="/tutorverse.svg" alt="TutorVerse.in" className="h-20 w-auto object-contain object-left"/><img src="/saralvigyan.svg" alt="Saral Vigyan" className="mt-4 h-12 w-auto object-contain object-left"/></div><div><b>Explore</b><div className="mt-3 grid gap-2 text-sm text-slate-500"><Link href="/demo">Schedule a Free Demo</Link><Link href="/subjects">Subjects & exams</Link><Link href="/tutors">Tutor search</Link><Link href="/how-it-works">How it works</Link></div></div><div><b>Learning</b><div className="mt-3 grid gap-2 text-sm text-slate-500"><Link href="/student-dashboard">Student dashboard</Link><Link href="/parent-dashboard">Parent dashboard</Link><Link href="/login">Login</Link></div></div><div><b>Join Saral Vigyan</b><div className="mt-3 grid gap-2 text-sm text-slate-500"><Link href="/become-a-tutor">Tutor application</Link><Link href="/admin">Admin</Link></div></div></div><div className="border-t border-slate-100 py-5 text-center text-xs text-slate-400">© {new Date().getFullYear()} TutorVerse.in · Powered by Saral Vigyan</div></footer>}
