'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

export function Header(){
  const [signedIn,setSignedIn]=useState(false);
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active)setSignedIn(!!data.session)});const {data:listener}=supabase.auth.onAuthStateChange((_e,session)=>setSignedIn(!!session));return()=>{active=false;listener.subscription.unsubscribe()}},[]);
  async function logout(){await supabase.auth.signOut();window.location.href='/login'}
  return <header className="sticky top-0 z-50 border-b border-[#dfe9e2] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-2.5"><Link href="/" className="shrink-0 rounded-xl"><img src="/tutorverse.svg" alt="TutorVerse.in" className="h-14 w-[118px] object-contain object-left sm:h-16 sm:w-[145px]"/></Link><div className="hidden items-center gap-3 xl:flex"><span className="text-[9px] font-black uppercase tracking-[.18em] text-[#899686]">Powered by</span><div className="rounded-xl bg-[#fffaf6] px-2 py-1"><img src="/saralvigyan.svg" alt="Saral Vigyan" className="h-9 w-[190px] object-contain object-left"/></div></div><nav className="hidden items-center gap-6 text-sm font-bold text-[#536174] lg:flex"><Link href="/demo" className="text-[#168c52]">Schedule a Free Demo</Link><Link href="/subjects" className="hover:text-[#168c52]">Subjects</Link><Link href="/become-a-tutor" className="hover:text-[#168c52]">Join as a Tutor</Link></nav><div className="flex items-center gap-1">{signedIn?<button onClick={logout} className="rounded-xl border border-[#d7e4da] px-3 py-2 text-sm font-black text-[#355141]">Log out</button>:<><Link href="/login" className="rounded-xl px-3 py-2 text-sm font-black text-[#536174]">Log in</Link><Link href="/signup" className="rounded-xl bg-[#1e9b58] px-4 py-2.5 text-sm font-black text-white shadow-md shadow-green-100">Get started</Link></>}</div></div></header>
}

export function Footer(){return <footer className="mt-20 border-t border-[#dfe9e2] bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 md:grid-cols-4"><div><img src="/tutorverse.svg" alt="TutorVerse.in" className="h-16 w-auto object-contain object-left"/><div className="mt-3 rounded-xl bg-[#fffaf6] px-2 py-1 inline-block"><img src="/saralvigyan.svg" alt="Saral Vigyan" className="h-11 w-[200px] object-contain object-left"/></div></div><div><b className="text-[#26384a]">Explore</b><div className="mt-3 grid gap-2 text-sm text-[#68758a]"><Link href="/demo">Schedule a Free Demo</Link><Link href="/subjects">Subjects & exams</Link><Link href="/tutors">Tutor search</Link><Link href="/how-it-works">How it works</Link></div></div><div><b className="text-[#26384a]">Learning</b><div className="mt-3 grid gap-2 text-sm text-[#68758a]"><Link href="/student-dashboard">Student dashboard</Link><Link href="/parent-dashboard">Parent dashboard</Link><Link href="/login">Login</Link></div></div><div><b className="text-[#26384a]">Join Saral Vigyan</b><div className="mt-3 grid gap-2 text-sm text-[#68758a]"><Link href="/become-a-tutor">Tutor application</Link><Link href="/admin">Admin</Link></div></div></div><div className="border-t border-[#edf2ee] py-5 text-center text-xs text-[#899686]">© {new Date().getFullYear()} TutorVerse.in · Powered by Saral Vigyan</div></footer>}
