'use client'

import { useEffect, useState } from 'react'
import { Header, Footer } from '../components/site'
import { supabase } from '../../lib/supabase'
import { getAccurateLocation } from '../../lib/location'
import { classes, subjects, competitiveExams, boards } from '../data'

const modes = ['Online', 'Home', 'Batch']
type LocationFields = { address_line:string; area:string; city:string; state:string; pincode:string; latitude:string; longitude:string; location_accuracy_m:string }
const arr=(v:any)=>Array.isArray(v)?v:[]

export default function TutorDashboard(){
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[locationSaving,setLocationSaving]=useState(false),[message,setMessage]=useState(''),[locationMessage,setLocationMessage]=useState(''),[email,setEmail]=useState(''),[tutorId,setTutorId]=useState<string|null>(null)
 const [form,setForm]=useState({full_name:'',phone:'',experience_years:'',bio:'',modes:[] as string[],grades:[] as string[],subjects:[] as string[],custom_subjects:'',boards:[] as string[],competitive_exams:[] as string[],max_travel_km:''})
 const [location,setLocation]=useState<LocationFields>({address_line:'',area:'',city:'',state:'',pincode:'',latitude:'',longitude:'',location_accuracy_m:''})
 useEffect(()=>{async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return}setEmail(user.email||'');const [{data:p,error:pe},{data:t,error:te}]=await Promise.all([supabase.from('profiles').select('full_name,phone').eq('id',user.id).single(),supabase.from('tutors').select('id,experience_years,bio,city,modes,address_line,area,state,pincode,latitude,longitude,location_accuracy_m,grades,boards,subjects,custom_subjects,competitive_exams,max_travel_km').eq('profile_id',user.id).maybeSingle()]);if(pe||te||!t){setMessage(pe?.message||te?.message||'Tutor profile could not be loaded.');setLoading(false);return}setTutorId(t.id);setForm({full_name:p?.full_name||'',phone:p?.phone||'',experience_years:t.experience_years==null?'':String(t.experience_years),bio:t.bio||'',modes:arr(t.modes),grades:arr(t.grades),subjects:arr(t.subjects).filter((x:string)=>!arr(t.custom_subjects).includes(x)),custom_subjects:arr(t.custom_subjects).join(', '),boards:arr(t.boards),competitive_exams:arr(t.competitive_exams),max_travel_km:t.max_travel_km==null?'':String(t.max_travel_km)});setLocation({address_line:t.address_line||'',area:t.area||'',city:t.city||'',state:t.state||'',pincode:t.pincode||'',latitude:t.latitude==null?'':String(t.latitude),longitude:t.longitude==null?'':String(t.longitude),location_accuracy_m:t.location_accuracy_m==null?'':String(t.location_accuracy_m)});setLoading(false)}load()},[])
 const toggle=(key:'modes'|'grades'|'subjects'|'boards'|'competitive_exams',value:string)=>setForm(f=>({...f,[key]:f[key].includes(value)?f[key].filter(x=>x!==value):[...f[key],value]}))
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user||!tutorId){setMessage('Please log in again.');setSaving(false);return}const custom=form.custom_subjects.split(',').map(x=>x.trim()).filter(Boolean);const {error:pe}=await supabase.from('profiles').update({full_name:form.full_name.trim(),phone:form.phone.trim()}).eq('id',user.id);const {error:te}=await supabase.from('tutors').update({experience_years:form.experience_years?Number(form.experience_years):null,bio:form.bio.trim()||null,modes:form.modes,grades:form.grades,boards:form.boards,subjects:[...form.subjects,...custom.filter(x=>!form.subjects.includes(x))],custom_subjects:custom,competitive_exams:form.competitive_exams,max_travel_km:form.max_travel_km?Number(form.max_travel_km):null,city:location.city.trim()||null,address_line:location.address_line.trim()||null,area:location.area.trim()||null,state:location.state.trim()||null,pincode:location.pincode.trim()||null,latitude:location.latitude?Number(location.latitude):null,longitude:location.longitude?Number(location.longitude):null,location_accuracy_m:location.location_accuracy_m?Number(location.location_accuracy_m):null}).eq('id',tutorId);setMessage(pe?.message||te?.message||'✓ Profile saved. Saral Vigyan can now review your details.');setSaving(false)}
 async function useApproximateLocation(){setLocationMessage('');setLocationSaving(true);try{const r=await getAccurateLocation();setLocation(x=>({...x,latitude:String(r.latitude),longitude:String(r.longitude),location_accuracy_m:String(r.accuracy_m)}));setLocationMessage('Location captured. Click Save profile to store it.')}catch(e){setLocationMessage(e instanceof Error?e.message:'Location could not be obtained.')}finally{setLocationSaving(false)}}
 async function logout(){await supabase.auth.signOut();window.location.href='/login'}
 if(loading)return <><Header/><main className="mx-auto max-w-5xl px-5 py-16"><p className="text-slate-500">Loading your tutor profile…</p></main><Footer/></>
 if(message&&!tutorId)return <><Header/><main className="mx-auto max-w-5xl px-5 py-16"><div className="rounded-3xl border border-rose-200 bg-rose-50 p-6 text-rose-700">{message}</div></main><Footer/></>
 const box=(title:string,items:string[],key:'modes'|'grades'|'subjects'|'boards'|'competitive_exams',cols='grid-cols-2 sm:grid-cols-3')=><fieldset className="md:col-span-2"><legend className="text-xs font-extrabold uppercase tracking-wider text-slate-500">{title}</legend><div className={`mt-3 grid ${cols} gap-2`}>{items.map(v=><label key={v} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-semibold"><input type="checkbox" checked={form[key].includes(v)} onChange={()=>toggle(key,v)}/>{v}</label>)}</div></fieldset>
 return <><Header/><main className="mx-auto max-w-7xl px-5 py-10"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-slate-400">Tutor dashboard</p><h1 className="mt-2 text-4xl font-black tracking-tight">Welcome, {form.full_name||'Tutor'}.</h1><p className="mt-2 text-slate-500">Complete your profile. Saral Vigyan reviews profiles before public listing.</p></div><button onClick={logout} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold">Log out</button></div>
 <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Your profile</p><h2 className="mt-2 text-2xl font-black">Profile details</h2><form onSubmit={save} className="mt-7 grid gap-5 md:grid-cols-2">
 <label className="text-sm font-bold">Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Email<input readOnly value={email} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal text-slate-500"/></label><label className="text-sm font-bold">Phone / WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Years of teaching experience<input type="number" min="0" value={form.experience_years} onChange={e=>setForm({...form,experience_years:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label>
 {box('Grades / classes you teach',classes,'grades','grid-cols-2 sm:grid-cols-4')}{box('Subjects',subjects,'subjects')}
 <label className="md:col-span-2 text-sm font-bold">Other subjects <span className="font-normal text-slate-400">(comma separated)</span><input value={form.custom_subjects} onChange={e=>setForm({...form,custom_subjects:e.target.value})} placeholder="e.g. Accountancy, Economics, Statistics" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label>
 {box('Boards',boards,'boards')}{box('Competitive exams',competitiveExams,'competitive_exams')}{box('Teaching mode',modes,'modes','grid-cols-2 sm:grid-cols-3')}
 <label className="text-sm font-bold">Maximum distance willing to travel (km)<input type="number" min="0" step="0.5" value={form.max_travel_km} onChange={e=>setForm({...form,max_travel_km:e.target.value})} placeholder="e.g. 10" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label>
 <div className="text-sm font-bold md:col-span-2"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><span>Teaching location</span><button type="button" onClick={useApproximateLocation} disabled={locationSaving} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">{locationSaving?'Getting location…':'Use my approximate location'}</button></div><p className="mt-1 text-xs font-normal text-slate-500">Used internally for tutor matching. Exact address is not public.</p></div>
 <label className="text-sm font-bold">Area / locality<input value={location.area} onChange={e=>setLocation({...location,area:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">City<input value={location.city} onChange={e=>setLocation({...location,city:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">State<input value={location.state} onChange={e=>setLocation({...location,state:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">PIN code<input value={location.pincode} onChange={e=>setLocation({...location,pincode:e.target.value})} inputMode="numeric" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><label className="text-sm font-bold md:col-span-2">Address / landmark<input value={location.address_line} onChange={e=>setLocation({...location,address_line:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><div className="rounded-2xl bg-slate-50 p-4 text-xs text-slate-500 md:col-span-2">{location.latitude&&location.longitude?<>Coordinates captured: <b>{location.latitude}, {location.longitude}</b>{location.location_accuracy_m?` (about ${location.location_accuracy_m} m accuracy)`:''}. For internal matching only.</>:'No coordinates captured yet.'}</div>{locationMessage&&<p className="text-sm font-semibold text-slate-600 md:col-span-2">{locationMessage}</p>}
 <label className="text-sm font-bold md:col-span-2">Profile / teaching bio<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} rows={6} placeholder="Qualifications, teaching experience, achievements and teaching approach." className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label><div className="md:col-span-2 flex flex-wrap items-center gap-3"><button disabled={saving} className="rounded-xl bg-slate-950 px-5 py-3 font-black text-white">{saving?'Saving…':'Save profile'}</button>{message&&<p className="text-sm font-semibold text-slate-600">{message}</p>}</div></form></section>
 <section className="mt-6 rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">Classes</p><h2 className="mt-2 text-xl font-black">No classes assigned yet</h2><p className="mt-2 text-sm leading-6 text-slate-500">Once Saral Vigyan assigns a real class, its schedule and controls will appear here.</p></section></main><Footer/></>
}