import Link from 'next/link';
import { Header, Footer } from './components/site'; import AIChat from './components/ai-chat'; import { subjects, competitiveExams } from './data';
export default function Home(){return <><Header/><main>
<section className="hero"><div className="hero-glow"/><div className="hero-copy"><div className="eyebrow">TutorVerse · Powered by Saral Vigyan</div><h1>Expert teaching.<br/><em>Personally managed.</em></h1><p>TutorVerse combines expert teaching, structured classes and personalised academic support through curated batches, home tuition and live online classes.</p><div className="hero-actions"><Link href="/signup" className="btn primary">Get started <span>→</span></Link><Link href="/tutors" className="btn ghost">Look for a Tutor</Link></div><div className="trust"><span>●</span> Mumbai · Navi Mumbai · Thane</div></div><div className="hero-card"><div className="card-top"><span>HOW WE HELP</span><b>01</b></div><h2>Tell Saral Vigyan what you need.</h2><div className="subject-pills"><span>Batch tuition</span><span>Home tuition</span><span>Online tuition</span><span>School boards</span><span>Competitive exams</span><span>Parent-connected LMS</span></div><Link href="/how-it-works" className="card-link">See how TutorVerse works <span>↗</span></Link></div></section>
<section className="strip"><div><strong>1.</strong><span>Tell us your learning need</span></div><div><strong>2.</strong><span>We curate the right support</span></div><div><strong>3.</strong><span>Start your classes</span></div><div><strong>4.</strong><span>Track progress together</span></div></section>
<section className="section"><div className="section-head"><div><div className="eyebrow">Managed learning</div><h2>One platform for the whole learning journey.</h2></div></div><div className="subject-grid"><Link className="subject-card" href="/tutors"><span className="number">01</span><h3>Look for a Tutor</h3><p>Managed tutor search — registration never means automatic public listing.</p><span className="arrow">↗</span></Link><Link className="subject-card" href="/student-dashboard"><span className="number">02</span><h3>Student LMS</h3><p>Classes, calendar, reports, materials, homework and assessments.</p><span className="arrow">↗</span></Link><Link className="subject-card" href="/parent-dashboard"><span className="number">03</span><h3>Parent Connect</h3><p>30-minute reminders, start/close alerts, attendance and results.</p><span className="arrow">↗</span></Link><Link className="subject-card" href="/become-a-tutor"><span className="number">04</span><h3>Join as a Tutor</h3><p>Apply with grades, subjects and competitive-exam expertise for Saral Vigyan review.</p><span className="arrow">↗</span></Link></div></section>
<section className="section"><div className="section-head"><div><div className="eyebrow">Subjects</div><h2>School subjects stay separate from competitive exams.</h2></div><Link href="/subjects">Explore all →</Link></div><div className="subject-grid">{subjects.map((s,i)=><Link className="subject-card" href={'/tutors?subject='+encodeURIComponent(s)} key={s}><span className="number">0{i+1}</span><h3>{s}</h3><p>School / academic subject</p><span className="arrow">↗</span></Link>)}</div></section>
<section className="section"><div className="section-head"><div><div className="eyebrow">Competitive exams</div><h2>Dedicated exam-preparation tracks.</h2></div></div><div className="subject-grid">{competitiveExams.map((s,i)=><Link className="subject-card" href={'/tutors?exam='+encodeURIComponent(s)} key={s}><span className="number">{String(i+1).padStart(2,'0')}</span><h3>{s}</h3><p>Exam preparation support</p><span className="arrow">↗</span></Link>)}</div></section>
<section className="dark-cta"><div><div className="eyebrow light">Communication is part of the system</div><h2>Parents should never wonder<br/>whether class happened.</h2><p>Thirty-minute reminders, tutor-confirmed class start and closure, attendance, reports and results — designed for parallel email and WhatsApp notifications.</p></div><Link href="/signup" className="btn lightbtn">Create your account →</Link></section>
</main><Footer/><AIChat/></>}
