import Link from 'next/link';
import { Header, Footer } from './components/site';
import { subjects } from './data';

export default function Home(){return <><Header/><main>
<section className="hero"><div className="hero-glow"/><div className="hero-copy"><div className="eyebrow">TutorVerse · Powered by Saral Vigyan</div><h1>Expert teaching.<br/><em>Personally managed.</em></h1><p>TutorVerse brings expert teaching, structured classes and personalised academic support together — through curated batches, home tuition and live online classes.</p><div className="hero-actions"><Link href="/signup" className="btn primary">Get started <span>→</span></Link><Link href="/tutors" className="btn ghost">Look for a Tutor</Link></div><div className="trust"><span>●</span> Mumbai · Navi Mumbai · Thane</div></div><div className="hero-card"><div className="card-top"><span>HOW WE HELP</span><b>01</b></div><h2>Tell Saral Vigyan what you need.</h2><div className="subject-pills"><span>Batch tuition</span><span>Home tuition</span><span>Online tuition</span><span>School boards</span><span>JEE · NEET · CUET</span></div><Link href="/how-it-works" className="card-link">See how TutorVerse works <span>↗</span></Link></div></section>
<section className="strip"><div><strong>1.</strong><span>Tell us your learning need</span></div><div><strong>2.</strong><span>We curate the right support</span></div><div><strong>3.</strong><span>Start your classes</span></div><div><strong>4.</strong><span>Track progress together</span></div></section>
<section className="section"><div className="section-head"><div><div className="eyebrow">Managed learning</div><h2>One platform for the whole learning journey.</h2></div></div><div className="subject-grid"><Link className="subject-card" href="/tutors"><span className="number">01</span><h3>Find a Tutor</h3><p>Paid, managed tutor search — not an open marketplace.</p><span className="arrow">↗</span></Link><Link className="subject-card" href="/student-dashboard"><span className="number">02</span><h3>Student LMS</h3><p>Classes, calendar, reports, materials, homework and assessments.</p><span className="arrow">↗</span></Link><Link className="subject-card" href="/parent-dashboard"><span className="number">03</span><h3>Parent Connect</h3><p>Class reminders, start/close alerts, attendance and results.</p><span className="arrow">↗</span></Link><Link className="subject-card" href="/become-a-tutor"><span className="number">04</span><h3>Join as a Tutor</h3><p>Apply to Saral Vigyan. Approval controls who is presented to students.</p><span className="arrow">↗</span></Link></div></section>
<section className="section"><div className="section-head"><div><div className="eyebrow">Subjects & exams</div><h2>School, competitive and specialised learning.</h2></div><Link href="/subjects">Explore subjects →</Link></div><div className="subject-grid">{subjects.map((s,i)=><Link className="subject-card" href={'/tutors?subject='+encodeURIComponent(s)} key={s}><span className="number">0{i+1}</span><h3>{s}</h3><p>Curated learning support</p><span className="arrow">↗</span></Link>)}</div></section>
<section className="dark-cta"><div><div className="eyebrow light">Built around communication</div><h2>Parents should never wonder<br/>whether class happened.</h2><p>Thirty-minute reminders, tutor-confirmed class start and closure, attendance, reports and results — with email and WhatsApp notifications.</p></div><Link href="/signup" className="btn lightbtn">Create your account →</Link></section>
</main><Footer/></>}
