-- TutorVerse core schema. Apply this migration in the production Supabase project.
create extension if not exists pgcrypto;

do $$ begin create type user_role as enum ('student','parent','tutor','admin','staff'); exception when duplicate_object then null; end $$;
do $$ begin create type class_status as enum ('scheduled','started','completed','cancelled','no_show'); exception when duplicate_object then null; end $$;
do $$ begin create type attendance_status as enum ('pending','attended','absent','late'); exception when duplicate_object then null; end $$;

create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role user_role not null default 'student', phone text, whatsapp_opt_in boolean default true, created_at timestamptz default now());
create table if not exists students (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id) on delete set null, grade text, board text, city text, school text, created_at timestamptz default now());
create table if not exists parents (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id) on delete set null, relationship text, created_at timestamptz default now());
create table if not exists parent_students (parent_id uuid references parents(id) on delete cascade, student_id uuid references students(id) on delete cascade, primary key(parent_id,student_id));
create table if not exists tutors (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id) on delete set null, approved boolean default false, experience_years int, bio text, city text, modes text[] default '{}', created_at timestamptz default now());
create table if not exists subjects (id uuid primary key default gen_random_uuid(), name text unique not null, active boolean default true);
create table if not exists competitive_exams (id uuid primary key default gen_random_uuid(), name text unique not null, active boolean default true);
create table if not exists tutor_subjects (tutor_id uuid references tutors(id) on delete cascade, subject_id uuid references subjects(id) on delete cascade, primary key(tutor_id,subject_id));
create table if not exists tutor_exams (tutor_id uuid references tutors(id) on delete cascade, exam_id uuid references competitive_exams(id) on delete cascade, primary key(tutor_id,exam_id));
create table if not exists tutor_applications (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, grades text[] default '{}', subjects text[] default '{}', competitive_exams text[] default '{}', teaching_modes text[] default '{}', experience_years int, bio text, status text default 'pending', admin_notes text, created_at timestamptz default now());
create table if not exists classrooms (id uuid primary key default gen_random_uuid(), name text not null, subject_id uuid references subjects(id), tutor_id uuid references tutors(id), mode text, location text, active boolean default true, created_at timestamptz default now());
create table if not exists classroom_students (classroom_id uuid references classrooms(id) on delete cascade, student_id uuid references students(id) on delete cascade, primary key(classroom_id,student_id));
create table if not exists classes (id uuid primary key default gen_random_uuid(), classroom_id uuid references classrooms(id) on delete cascade, starts_at timestamptz not null, ends_at timestamptz not null, status class_status default 'scheduled', started_at timestamptz, closed_at timestamptz, meeting_url text, created_by uuid references profiles(id), updated_at timestamptz default now());
create table if not exists attendance (id uuid primary key default gen_random_uuid(), class_id uuid references classes(id) on delete cascade, student_id uuid references students(id) on delete cascade, status attendance_status default 'pending', marked_by uuid references profiles(id), marked_at timestamptz, unique(class_id,student_id));
create table if not exists class_reports (id uuid primary key default gen_random_uuid(), class_id uuid references classes(id) on delete cascade, topic text, covered text, homework text, tutor_remarks text, created_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists parent_acknowledgements (id uuid primary key default gen_random_uuid(), report_id uuid references class_reports(id) on delete cascade, parent_id uuid references parents(id) on delete cascade, seen_at timestamptz default now(), unique(report_id,parent_id));
create table if not exists feedback (id uuid primary key default gen_random_uuid(), classroom_id uuid references classrooms(id) on delete cascade, student_id uuid references students(id), parent_id uuid references parents(id), rating int, comment text, routed_to_admin boolean default true, created_at timestamptz default now());
create table if not exists content_items (id uuid primary key default gen_random_uuid(), classroom_id uuid references classrooms(id) on delete cascade, title text not null, content_type text, url text, description text, created_by uuid references profiles(id), created_at timestamptz default now());
create table if not exists homework (id uuid primary key default gen_random_uuid(), classroom_id uuid references classrooms(id) on delete cascade, title text not null, description text, due_at timestamptz, created_by uuid references profiles(id), created_at timestamptz default now());
create table if not exists assessments (id uuid primary key default gen_random_uuid(), title text not null, subject_id uuid references subjects(id), duration_minutes int not null, starts_at timestamptz, ends_at timestamptz, positive_marks numeric default 1, negative_marks numeric default 0, unanswered_marks numeric default 0, instructions text, published boolean default false, created_by uuid references profiles(id), created_at timestamptz default now());
create table if not exists assessment_questions (id uuid primary key default gen_random_uuid(), assessment_id uuid references assessments(id) on delete cascade, question_type text not null, prompt text not null, options jsonb, correct_answer jsonb, positive_marks numeric, negative_marks numeric, position int not null, image_url text, created_at timestamptz default now());
create table if not exists assessment_assignments (assessment_id uuid references assessments(id) on delete cascade, student_id uuid references students(id) on delete cascade, primary key(assessment_id,student_id));
create table if not exists assessment_attempts (id uuid primary key default gen_random_uuid(), assessment_id uuid references assessments(id) on delete cascade, student_id uuid references students(id) on delete cascade, started_at timestamptz, submitted_at timestamptz, score numeric, correct_count int, incorrect_count int, unanswered_count int, status text default 'not_started');
create table if not exists assessment_answers (id uuid primary key default gen_random_uuid(), attempt_id uuid references assessment_attempts(id) on delete cascade, question_id uuid references assessment_questions(id) on delete cascade, answer jsonb, is_correct boolean, marks_awarded numeric, evaluation_status text default 'auto');
create table if not exists payments (id uuid primary key default gen_random_uuid(), student_id uuid references students(id), amount numeric not null, currency text default 'INR', provider text, provider_payment_id text, status text default 'pending', created_at timestamptz default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), recipient_profile_id uuid references profiles(id) on delete cascade, event_type text not null, channel text not null, subject text, body text, related_class_id uuid references classes(id), related_report_id uuid references class_reports(id), status text default 'queued', sent_at timestamptz, created_at timestamptz default now());

create index if not exists idx_classes_starts_at on classes(starts_at);
create index if not exists idx_notifications_recipient on notifications(recipient_profile_id,created_at desc);
create index if not exists idx_attendance_student on attendance(student_id);
