'use client';
import { useEffect, useMemo, useState } from 'react';
import { Header, Footer } from '../components/site';
import { supabase } from '../../lib/supabase';
interface PublicTutor { id:string; name:string|null; subjects:string[]|null; bio:string|null }
export default function Tutors(){
 const [tutors,setTutors]=useState<PublicTutor[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.rpc('public_approved_tutors');if(error){setError(error.message);setTutors([])}else setTutors((data||[]) as PublicTutor[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const term=q.trim().toLowerCase();return tutors.filter(t=>!term||[t.name,...(t.subjects||[]),t.bio].filter(Boolean).join(' ').toLowerCase().includes(term))},[tutors,q]);
 return <><Header/><main className="page"><div className="page-intro"><div><div className="eyebrow">Approved tutor directory</div><h1>Find a Tutor</h1><p>Browse our approved tutor profiles. Personal contact details are kept private; Saral Vigyan coordinates introductions and demo requests.</p></div><span className="count">{filtered.length} tutors</span></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name or subject…"/><button type="button" className="btn ghost" onClick={load}>Refresh</button></div>{error&&<div className="empty"><h2>Unable to load tutor directory.</h2><p>{error}</p></div>}{loading?<div className="empty"><p>Loading approved tutors…</p></div>:!error&&<div className="tutor-grid">{filtered.map(t=><article className="tutor-card" key={t.id}><div className="avatar">{(t.name||'Tutor').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div className="tutor-meta"><h2>{t.name||'Tutor'}</h2><b>{(t.subjects||[]).join(' · ')||'Subject details available on request'}</b><p>{t.bio||'Tutor profile summary available on request.'}</p></div></article>)}</div>}{!loading&&!error&&!filtered.length&&<div className="empty"><h2>No approved tutors match that search.</h2><button className="btn primary" onClick={()=>setQ('')}>Show all tutors</button></div>}</main><Footer/></>}
